export const hundredWordsArray = [
    'apple', 'banana', 'orange', 'grape', 'kiwi',
    'elephant', 'giraffe', 'zebra', 'lion', 'tiger',
    'sun', 'moon', 'stars', 'planet', 'galaxy',
    'book', 'pen', 'paper', 'notebook', 'pencil',
    'computer', 'keyboard', 'mouse', 'monitor', 'laptop',
    'ocean', 'mountain', 'river', 'forest', 'desert',
    'red', 'blue', 'green', 'yellow', 'purple',
    'happy', 'sad', 'angry', 'excited', 'calm',
    'music', 'art', 'dance', 'film', 'photography',
    'coffee', 'tea', 'juice', 'water', 'soda',
    'football', 'basketball', 'soccer', 'tennis', 'golf',
    'flower', 'tree', 'grass', 'cloud', 'rain',
    'friend', 'family', 'love', 'laughter', 'happiness',
    'school', 'work', 'play', 'study', 'learn',
    'travel', 'adventure', 'explore', 'discover', 'journey',
    'sunrise', 'sunset', 'morning', 'night', 'day',
    'smile', 'laugh', 'cry', 'sing', 'dance'
  ];